# ╔╗─╔╦═╗╔═╦═══╗╔╗──────╔╗
# ║║─║║║╚╝║║╔═╗║║║──────║║
# ║╚═╝║╔╗╔╗║║─╚╝║║──╔╦═╗║║╔╗
# ║╔═╗║║║║║║║─╔╗║║─╔╬╣╔╗╣╚╝╝
# ║║─║║║║║║║╚═╝║║╚═╝║║║║║╔╗╗
# ╚╝─╚╩╝╚╝╚╩═══╝╚═══╩╩╝╚╩╝╚╝

# Connection settings
connection:
  # The ip and port
  ip: 'localhost'
  port: 1337