name: '${name}'
version: '${version}'
author: 'Skyslycer'
description: 'The Minecraft part of the HMC Link messaging system'

main: 'de.skyslycer.hmclink.plugin.HMCLinkPlugin'

api-version: '1.18'

softdepend:
  - 'PlaceholderAPI'

permissions:
  hmclink.unlinkothers:
    description: 'Gives you the ability to unlink other players.'
    default: op